<!-- TODO finish this.. might be used using TemplateFunctions->includeTemplate(..);-->
<div class="helper-pagination">
    <table>
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ([] as $row) { ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>            
            <?php } ?>
        </tbody>
    <table>
</div>